import Head from 'next/head'
import Image from 'next/image'
import About from '../components/About'
import Main from '../components/Main'
import Skills from '../components/Skills'
import Contact from '../components/Contact'
import Projects from '../components/Projects'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Chris | Solution Engineer</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Main />
      <About />
      <Skills />
      <Projects />
      <Contact />
    </div>
  )
}
